name: Perf Benchmarks

on:
  pull_request:
    branches:
      - main
    paths-ignore: [ '**.md' ]
  push:
    branches:
      - main
    paths-ignore: [ '**.md' ]

jobs:
  benchmark:
    name: Relative performance benchmarking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Run benchmark via JMH gradle plugin https://github.com/melix/jmh-gradle-plugin
      - name: Run benchmark
        run: |
          ./gradlew jmh

      # Run `github-action-benchmark` action
      - name: Add benchmark PR job summary
        uses: benchmark-action/github-action-benchmark@v1.18.0
        with:
          # What benchmark tool the output.txt came from
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: library/build/reports/jmh/results.json

          # Where the previous data file is stored
          # external-data-json-path: ./cache/benchmark-data.json

          # GitHub API token to make a commit comment or job summary
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable Job Summary for PRs
          summary-always: true
          comment-always: true
          #
          alert-threshold: "150%"
          # Workflow will fail when an alert happens
          fail-on-alert: false
          # Enable alert commit comment
          comment-on-alert: true
          # Save to github pages
          auto-push: ${{ github.event_name == 'push' }}
          gh-pages-branch: gh-pages # this is the default

          # benchmark graphs available at https://databiosphere.github.io/java-pfb/dev/bench/
          benchmark-data-dir-path: docs/dev/bench

          save-data-file: ${{ github.event_name == 'push' }}
