name: Perf Benchmarks

on:
  pull_request:
    branches:
      - main
    paths-ignore: [ '**.md' ]
  push:
    branches:
      - main
    paths-ignore: [ '**.md' ]

jobs:
  benchmark:
    name: Relative performance benchmarking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Run benchmark via JMH gradle plugin https://github.com/melix/jmh-gradle-plugin
      - name: Run benchmark
        run: |
          ./gradlew jmh

      # For merges to main, update github pages with benchmarks against the main branch
      - name: Update benchmarks for main branch
        uses: benchmark-action/github-action-benchmark@v1.18.0
        if: github.event_name == 'push'
        with:
          # What benchmark tool the output.txt came from
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: library/build/reports/jmh/results.json
          # GitHub API token to make a commit comment or job summary
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Workflow will not fail when an alert happens
          fail-on-alert: false
          # Enable alert commit comment
          comment-on-alert: true
          # Save to github pages
          auto-push: true
          gh-pages-branch: gh-pages # this is the default
          benchmark-data-dir-path: docs/dev/bench
          save-data-file: true


      # For PRs, add commit comments for the PR branch's benchmarks
      - name: Add benchmark PR job summary
        uses: benchmark-action/github-action-benchmark@v1.18.0
        if: github.event_name == 'pull_request'
        with:
          # What benchmark tool the output.txt came from
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: library/build/reports/jmh/results.json
          # GitHub API token to make a commit comment or job summary
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable Job Summary for PRs
          summary-always: false
          comment-always: true
          alert-threshold: "150%"
          # Workflow will not fail when an alert happens
          fail-on-alert: false
          # Enable alert commit comment
          comment-on-alert: true
          # Don't persist PR benchmarks
          auto-push: false
          save-data-file: false
