name: Publish Library to Artifactory
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter a valid tag for the release'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      BROADBOT_TOKEN:
        required: true
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: broad-dsp-gcr-public

jobs:
  publish-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # ref: ${{ inputs.tag }}
          ref: core-593-jfrog-to-gar
          token: ${{ secrets.BROADBOT_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-artifact-registry-push@dsp-artifact-registry.iam.gserviceaccount.com'
      - name: Publish client to GAR
        run: ./gradlew publish
        env:
          GOOGLE_CLOUD_PROJECT: dsp-artifact-registry
          GAR_LOCATION: us-central1
          GAR_REPOSITORY_ID: libs-release-standard

      # - name: Publish Library Artifactory
      #   run: ./gradlew --build-cache artifactoryPublish
      #   env:
      #     ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      #     ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      #     ARTIFACTORY_REPO_KEY: "libs-release-local"
