name: Create Github Release with CLI Jar and Distribution
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build jar with latest tagged version
        run: |
          ./gradlew --build-cache :cli:jar
          ./gradlew --build-cache :cli:assembleDist
      - name: Create tagged release with CLI jar
        run: gh release create ${{ inputs.tag }} 'cli/build/libs/java-pfb-cli-${{ inputs.tag }}.jar' 'cli/build/distributions/cli-${{ inputs.tag }}.zip' --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack on failure
        uses: broadinstitute/action-slack@v3.8.0
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#dsp-analysis-journeys-alerts'
          status: failure
          author_name: Create Github Release with CLI Jar
          fields: job
          text: 'Publish failed :sadpanda:'
          username: 'Java-PFB GitHub Action'